// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxwhAkzN9hFegUpr9xkG8CHPmse1gzhS0',
    appId: '1:839770731538:web:666bf12028340cfb3354cb',
    messagingSenderId: '839770731538',
    projectId: 'velora-brew',
    authDomain: 'velora-brew.firebaseapp.com',
    storageBucket: 'velora-brew.firebasestorage.app',
    measurementId: 'G-634T633KN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK0UUZN76_zblvODG_0Mmbhdal-dc_Nzs',
    appId: '1:839770731538:android:ef44daebbd7e93823354cb',
    messagingSenderId: '839770731538',
    projectId: 'velora-brew',
    storageBucket: 'velora-brew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg_ppQG56nD5s0U2Rg4DMZqB3P-WQ4mfQ',
    appId: '1:839770731538:ios:69d188b9cc9751a63354cb',
    messagingSenderId: '839770731538',
    projectId: 'velora-brew',
    storageBucket: 'velora-brew.firebasestorage.app',
    iosBundleId: 'com.example.veloraBrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg_ppQG56nD5s0U2Rg4DMZqB3P-WQ4mfQ',
    appId: '1:839770731538:ios:69d188b9cc9751a63354cb',
    messagingSenderId: '839770731538',
    projectId: 'velora-brew',
    storageBucket: 'velora-brew.firebasestorage.app',
    iosBundleId: 'com.example.veloraBrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxwhAkzN9hFegUpr9xkG8CHPmse1gzhS0',
    appId: '1:839770731538:web:8deb1bb4d37502393354cb',
    messagingSenderId: '839770731538',
    projectId: 'velora-brew',
    authDomain: 'velora-brew.firebaseapp.com',
    storageBucket: 'velora-brew.firebasestorage.app',
    measurementId: 'G-4DB4ZB71R7',
  );
}
